# Generated by Django 5.2.5 on 2025-08-27 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('location', models.CharField(max_length=100, verbose_name='Local')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date_taken', models.DateField(verbose_name='Data da Viagem')),
                ('image', models.ImageField(upload_to='galeria/images/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-date_taken'],
            },
        ),
    ]
